services:
  mariadb:
    env_file:
      - compose.env
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  spring-api:
    env_file:
      - compose.env
    build:
      context: ./spring-server
    container_name: spring-api
    restart: always
    depends_on:
      - mariadb
    ports:
      - ${API_PORT}:8080
    environment:
      SPRING_DATASOURCE_URL: ${API_DATASOURCE_URL}?characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SERVLET_MULTIPART_ENABLED: "true"
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "100MB"
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "500MB"

      SERVER_TOMCAT_MAX_SWALLOW_SIZE: "-1"
      SERVER_TOMCAT_MAX_HTTP_FORM_POST_SIZE: "500MB"

      GOV_KEY_ENCODED: ${GOV_KEY_ENCODED}
      GOV_KEY_DECODED: ${GOV_KEY_DECODED}

  ai-server:
    env_file:
      - compose.env
    build:
      context: ./ai-server
    container_name: ai-server
    restart: always
    ports:
      - ${AI_PORT}:8000

volumes:
  mariadb_data:
